class CaregaverModel {
  String imageUrl;
  String firstName;
  int age;
  String nationality;
  double distance;
  double rating;
  String providedHoursOfCare;
  String clientRef;
  String qualifications;
  List<String> badgesIcons;
  String aboutMe;
  String location;
  List<String> providedServices;
  List<String> supProvidedServices;
  List<String> additionalServices;
  List<String> ratingReviewsAndReferences;
  List<String> experience;
  List<String> supExperience;
  List<String> qualificationsEducation;
  List<String> fees;
  List<String> supFees;
  List<String> avallabillty;
  List<String> generalAvallabillty;
  List<String> specialRemarks;
  List<String> documents;
  List<String> additionalInformation;
  CaregaverModel({
    required this.imageUrl,
    required this.firstName,
    required this.age,
    required this.nationality,
    required this.distance,
    required this.rating,
    required this.providedHoursOfCare,
    required this.clientRef,
    required this.qualifications,
    required this.badgesIcons,
    required this.aboutMe,
    required this.location,
    required this.providedServices,
    required this.supProvidedServices,
    required this.additionalServices,
    required this.ratingReviewsAndReferences,
    required this.experience,
    required this.supExperience,
    required this.qualificationsEducation,
    required this.fees,
    required this.supFees,
    required this.avallabillty,
    required this.generalAvallabillty,
    required this.specialRemarks,
    required this.documents,
    required this.additionalInformation,
  });
}
